language: php

php:
  - 7.2
before_install:
  - composer self-update

install:
  - rm composer.lock
  - travis_retry composer update --prefer-dist
  
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - composer dumpautoload -o
